/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.CharBuffer;

public class App {

  public static void main(String[] args) throws IOException {
    App app = new App();
    app.run();
  }

  private void run() throws IOException {
    // 1. Listen
    int port = 8080;
    ServerSocket listener = new ServerSocket(port, 0);
    System.out.println("Listen");
    // 2. Accept
    while (true){
      Socket socket = listener.accept();
      System.out.println("Accept");
      // 3. Request -> Response
      Reader reader = new InputStreamReader(socket.getInputStream());
      CharBuffer charBuffer = CharBuffer.allocate(1_000_000);
      reader.read(charBuffer);
      charBuffer.flip();
      System.out.println(charBuffer.toString());

      String message = """
        HTTP/1.1 200 OK
        
        Hello, World!
        """;

      Writer writer = new OutputStreamWriter(socket.getOutputStream());
      writer.write(message);
      writer.flush();
      // 4. Close
      socket.close();
    }
  }
}
